def fail(msg):
  raise Exception(msg)
